#!/bin/bash
set -e

OTOOL=${HOST}-otool INSTALLNAMETOOL=${HOST}-install_name_tool STRIP=${HOST}-strip contrib/macdeploy/macdeployqtplus 1337-Qt.app
mkdir -p dist/.background
install contrib/macdeploy/background.png dist/.background
install contrib/macdeploy/DS_Store dist/.DS_Store
install src/qt/res/icons/bitcoin.icns dist/.VolumeIcon.icns
cd dist
ln -sf /Applications Applications
cd ..
genisoimage -no-cache-inodes -l -probe -V "1337" -no-pad -r -apple -o 1337.tmp.dmg dist
dmg dmg 1337.tmp.dmg 1337.macosx.dmg
